### PR TITLE
Add punch hole & black background options

### PR DESCRIPTION
**Pull request by Iksas**
This PR adds the following options:
- punch holes (DIN A4 and US Letter)
- black background (phone apps sometimes create a black background when scanning)

The "Border" setting has been renamed to "Background".

The new options:
settings

The output (A4 punch holes, Black Border):
hole_white
The output (A4 punch holes, Black):
hole_black

Note: The coordinates of the punch holes have been hard coded, since there is no way to find out the height of the page in the npm version of ImageMagick (the `%[fx:]` [operator](https://imagemagick.org/script/fx.php) doesn't work). The hard coded coordinates worked fine with every PDF I tested, since the number of pixels is the same after each PDF is rasterized with the same DPI.

### CODE REVIEW

**Comment by Iksas** [comment]
I [read](https://vuetifyjs.com/en/components/radio-buttons/#direction) that you could add `row` to a `v-radio-group` to create horizontal radio buttons:

https://github.com/rwv/lookscanned.io/blob/1683a88e5f42b60f8b91095b1e3576107f66b097/src/components/ScanSettings/Settings/PunchHoleSetting.vue#L5-L6

But it didn't work, the only solution I found was to change some CSS to get horizontal radio buttons:

https://github.com/rwv/lookscanned.io/blob/1683a88e5f42b60f8b91095b1e3576107f66b097/src/components/ScanSettings/Settings/PunchHoleSetting.vue#L49-L61

@rwv if you know how to get horizontal radio buttons without changing the CSS, let me know, I'd be interested.

**Comment by rwv** [comment]
This may related to vuetify is still in beta and there are ton of bugs.  But i will still have a try!

**Comment by rwv** [comment]
A perfect circle of punch hole seems too fake? Could we use a transparent PNG for better look?

**Comment by rwv** [comment]
Also we could get image height and width using canvas h&w.

**Comment by rwv** [comment]
> I [read](https://vuetifyjs.com/en/components/radio-buttons/#direction) that you could add `row` to a `v-radio-group` to create horizontal radio buttons:

https://next.vuetifyjs.com/en/api/v-radio-group/

Here is Vuetify 3 doc which introduces some breaking changes.

**Comment by Iksas** [comment]
> Use `inline` attribute instead.

Thanks, that's what I needed! I'll edit the files.

> A perfect circle of punch hole seems too fake? Could we use a transparent PNG for better look?

Yes, that would be a good option. I don't know how to get local file paths of PNG files in JavaScript though.

> Also we could get image height and width using canvas h&w.

I tried to implement something like this, but I couldn't do it. 

I don't know enough about JavaScript, so I would need some help/tips on how to solve these two problems. Or you can implement the solutions yourself, if you want.

**Comment by Iksas** [comment]
Thank you!

**Comment by rwv** [comment]
I merged this PR to branch `punchholes` for now.

**Pull request merged**
