### PR TITLE
Add File System Access API support for saving

### PR DESCRIPTION
**Pull request by tomayac**
On browsers that support the [File System Access API](https://web.dev/file-system-access/), this allows the user to select their desired save folder, for example `~/Documents/look-scanned`,  which is why the button text was changed from **Download** to **Save**). On browsers that don't support the API, the files will continue transparently going straight into the user's default downloads folder, as before.

Screen Shot 2022-04-25 at 15 34 53

### CODE REVIEW

**Comment by tomayac** [comment]
@rwv Do you think this can land? Thank you!

**Comment by rwv** [comment]
Thank you for this PR! This can land definitely. I have a very busy last week and sorry for not replying to you sooner.

**Comment by tomayac** [comment]
Woohoo, thank you! Also such a great tool! `<3`

**Comment by tomayac** [comment]
(If you have a moment, could you please deploy a new build? Thank you!)

**Comment by rwv** [comment]
I am deploying a new build right now, eta 5 minutes

**Comment by tomayac** [comment]
`<3` Brilliant! Have a great day!

**Comment by rwv** [comment]
I change blobPromise to blob for fileSave(). 
I think it is a little confusing if a user select a path to save but need to wait file to generate and save. 
https://github.com/rwv/lookscanned.io/commit/fe421d62cf904790df029f2a75c555101321462c

**Comment by rwv** [comment]
Deployed: https://lookscanned.io/scan
Service worker update and activate required. You may need to fully close all lookscanned.io tabs and reopen it.

**Comment by tomayac** [comment]
Please see https://github.com/rwv/lookscanned.io/commit/fe421d62cf904790df029f2a75c555101321462c#commitcomment-72751594.

**Pull request merged**
